### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by borxes** [samarjeet27/CSV-Mapper#6]
In the installation instructions it says
git clone http://github.com/samarjeet27

While it should be 
git clone http://github.com/samarjeet27/CSV-Mapper

**Comment by samarjeet27** [comment]
Oh yeah, I missed that out.

Fixed in https://github.com/samarjeet27/CSV-
Mapper/commit/ea46fbdbf7b5742b4bd95a8fe5b6805d96ccad9c

Thanks for reporting :')
Cheers 👍
